correctness check
Signed-off-by: Terry Kong <terryk@nvidia.com>

diff --git a/.github/workflows/cicd-main.yml b/.github/workflows/cicd-main.yml
--- a/.github/workflows/cicd-main.yml
+++ b/.github/workflows/cicd-main.yml
@@ -128,6 +128,16 @@ jobs:
           uv venv
           uv run --group dev pre-commit install
           uv run --group dev pre-commit run --all-files --show-diff-on-failure --color=always
+      # TODO: this is a temporary check and should be removed once we have 100% correctness
+      - name: Check if any files with zero errors not in whitelist
+        run: |
+          for file in $(uv run --group dev pyrefly check $(git ls-files 'nemo_rl/**/*.py' 'examples/**/*.py' 'docs/*.py' 'tools/**/*.py') --output-format json | jq -r --slurpfile all_files <(git ls-files 'nemo_rl/**/*.py' 'examples/**/*.py' 'docs/*.py' 'tools/**/*.py' | jq -R -s 'split("\n")[:-1]') '(.errors | group_by(.path) | map({(.[0].path | sub("/home/terryk/nemo-rl/"; "")): length}) | add // {}) as $error_counts | $all_files[0][] | . as $file | if ($error_counts[$file] // 0) == 0 then $file else empty end'); do
+            if ! fgrep -q "$file" pyrefly.toml; then
+              echo "File $file has zero errors but is not in pyrefly.toml in the 'project-includes' list. Please add it to this whitelist."
+              exit 1
+            fi
+          done
+          echo "All files accounted for!"
       - name: Minimize uv cache
         run: uv cache prune --ci
 
